//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvSeries.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userlogin
    {
        public string tv_username { get; set; }
        public int tv_userID { get; set; }
        public string tv_userpass { get; set; }
        public string tv_image { get; set; }
    
        public virtual tv_UserSerie tv_UserSerie { get; set; }
    }
}
