//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvSeriesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Series
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Series()
        {
            this.tv_UserSerie = new HashSet<tv_UserSerie>();
        }
    
        public int serie_id { get; set; }
        public string serie_name { get; set; }
        public string serie_date { get; set; }
        public double serie_rating { get; set; }
        public string serie_link { get; set; }
        public string serie_image { get; set; }
        public Nullable<int> serie_episode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tv_UserSerie> tv_UserSerie { get; set; }
    }
}
